# Generated by Django 6.0.6 on 2026-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.IntegerField()),
                ('day_date', models.DateField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(default='Unknown', max_length=120)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('issues', models.JSONField(default=list)),
                ('raw', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['day_date', 'start'],
            },
        ),
    ]
