# Generated by Django 6.0.6 on 2026-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120, unique=True)),
                ('group_label', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['group_label', 'reason'],
            },
        ),
    ]
