# Generated by Django 6.0.6 on 2026-07-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_reasongroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='Sample dataset', max_length=255)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
    ]
